function SimCtrl() {
	this.roundsPerTrial = 1;
	this.numTrials = 1;
	this.betAmt = 5;
	this.passLine = true;
	this.betFour = 0;
	this.betFive = 0;
	this.betSix = 0;
	this.betEight = 0;
	this.betNine = 0;
	this.betTen = 0;
	this.disableButton = false;
	this.resLog = '';
	this.simLog = '';
	this.errArr = [];
	this.isLoading = false;
	this.showMoreTrialResults = [];
	this.trialResultCounter = 1;
}