angular.module('core', [])
	.controller('simCtrl', SimCtrl)
	.directive('runSim', ['$q', '$timeout', runSim])
	.directive('appendResult', ['$q', '$timeout', '$compile', appendResult])
	.directive('showMoreTrial', ['$compile', showMoreTrial])
	.filter('trusted', ['$sce', trusted])